import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

class LanguageService extends ChangeNotifier {
  static final LanguageService _instance = LanguageService._internal();
  factory LanguageService() => _instance;
  LanguageService._internal();

  String _currentLanguage = 'English';
  
  String get currentLanguage => _currentLanguage;

  final Map<String, Map<String, String>> _translations = {
    'English': {
      // Login & Common
      'login': 'Sign In',
      'username': 'Username',
      'password': 'Password',
      'forgot_password': 'Forgot Password?',
      'dont_have_account': "Don't have an account? ",
      'create_account': 'Create Account',
      'verifying': 'Verifying...',
      'username_hint': 'Enter your preferred username',
      'password_hint': 'Enter your secure password',
      'brgy_title': 'Brgy. Balintawak, Lipa City',
      'app_name': 'Garbage Tracker',
      'terms': 'Terms & Conditions',
      'privacy': 'Privacy Policy',
      'select_language': 'Select your language',
      'logout': 'Logout',
      'cancel': 'Cancel',
      'save': 'Save Changes',
      'edit': 'Edit',
      'close': 'Close',
      'back': 'Back',
      'next': 'Next',
      'success': 'Success',
      'error': 'Error',
      'all_rights_reserved': 'All rights reserved',

      // Legal Modals
      'terms_title': 'Terms & Conditions',
      'privacy_title': 'Privacy Policy',
      'legal_accept': 'I Accept',
      'legal_decline': 'Decline',

      // Registration
      'register': 'Register',
      'choose_role': 'Choose Your Role',
      'select_account_type': 'Select your account type to continue',
      'resident': 'Resident',
      'resident_sub': 'Track trucks and file complaints',
      'driver': 'Driver',
      'driver_sub': 'Manage routes and track collections',
      'resident_reg': 'Resident Registration',
      'driver_reg': 'Driver Registration',
      'full_name': 'Full Name',
      'email': 'Email Address',
      'phone': 'Contact Number',
      'purok': 'Purok / Area',
      'address': 'Complete Address',
      'license': 'License Number',
      'plate': 'Plate Number',
      'preferred_truck': 'Preferred Truck',
      'register_btn': 'Create Account',
      'already_have_account': 'Already have an account? ',

      // Forgot Password (3 Steps)
      'account_recovery': 'Account Recovery',
      'verification': 'Verification',
      'enter_token': 'Enter Token',
      'step_1_title': 'Reset Password',
      'step_2_title': 'Verify Token',
      'step_3_title': 'Create New',
      'step_1_of_3': 'Step 1 of 3: Verify your identity',
      'step_2_of_3': 'Step 2 of 3: Enter the 6-digit code',
      'step_3_of_3': 'Step 3 of 3: Secure your account',
      'send_verification': 'Send Verification',
      'verify_token_btn': 'Verify Token',
      'reset_password_btn': 'Reset Password',
      'confirm_password': 'Confirm Password',
      'otp_hint': '000000',
      'code_sent_to': 'Code sent to:',

      // Dashboards (Resident)
      'home': 'Home',
      'track': 'Track',
      'complaints': 'Complaints',
      'settings': 'Settings',
      'welcome_back': 'Welcome Back 👋',
      'active_trucks': 'Active Trucks',
      'estimated_time': 'Estimated Time',
      'real_time_overview': 'Real-time Overview',
      'live_tracking': 'Live Tracking',
      'full_map': 'Full Map',
      'quick_actions': 'Quick Actions',
      'track_trucks': 'Track Trucks',
      'file_complaint': 'File Complaint',

      // Admin Panel
      'admin_panel': 'Admin Dashboard',
      'analytics': 'Analytics',
      'user_mgmt': 'User Management',
      'data_mgmt': 'Data Management',
      'system_logs': 'System Logs',
      'active_fleet': 'Active Fleet',
      'coverage': 'Coverage',
      'routes_done': 'Routes Done',
      'issues': 'Issues',

      // Settings Specifics
      'profile_info': 'Profile Information',
      'notifications': 'Notifications',
      'push_notifications': 'Push Notifications',
      'account_privacy': 'Account & Privacy',
      'change_password': 'Change Password',
      'help_support': 'Help & Support',
      'faqs': 'FAQs',
      'contact_support': 'Contact Support',
      'about': 'About',
      'app_info': 'App Information',
      'language': 'Language',
      'sign_out_q': 'Sign Out?',
      'sign_out_confirm': 'Are you sure you want to end your session?',

      // Registration Additional
      'purok_hint': 'Select your Purok',
      'address_hint': 'Enter your complete address',
      'email_hint': 'example@email.com',
      'phone_hint': '09XXXXXXXXX',
      'license_hint': 'Driver License Number',
      'plate_hint': 'Truck Plate Number',

      // 2FA Screen
      'two_step_verification': 'Two-Step Verification',
      'enter_6_digit': 'Enter the 6-digit code sent to your email:',
      'verify_login': 'Verify & Login',
      'resend_code': 'Resend Code',
      'back_to_login': 'Back to Login',
      'please_enter_otp': 'Please enter the 6-digit code',
      'otp_sent_success': 'New code sent successfully!',
      'otp_verify_success': 'Verification successful!',

      // Driver Dashboard Details
      'vehicle_controls': 'Vehicle Controls',
      'start_trip': 'START',
      'pause_trip': 'PAUSE',
      'full_truck': 'FULL',
      'finish_trip': 'DONE',
      'collection_progress': 'Collection Progress',
      'manual_alert': 'Manual Alert',
      'simulation_mode': 'Simulation Mode',
      'real_gps': 'Real GPS',
      'view_all_puroks': 'View All Puroks',
      'show_less': 'Show Less',
      'alert_history': 'Alert History',
      'trip_finished_success': 'Trip Finished successfully.',
      'finish_trip_q': 'Finish Trip?',
      'confirm_finish': 'Are you sure you want to finish the trip?',

      // Resident Dashboard Details
      'no_notifications': 'No notifications found.',
      'approaching': 'Approaching',
      'no_active_collection': 'No active collection',
      'real_time_locations': 'Real-time truck locations',
      'verification_token': 'Verification Token',
      'new_password': 'New Password',
      'manage_preferences': 'Manage your preferences',
      'receive_notifications': 'Receive updates on truck arrivals',
      'version': 'Version',
      'last_updated': 'Last Updated',
      'data_management': 'Data Management',
      'view_my_data': 'View My Data',
      'clear_cache': 'Clear Local Cache',
      'delete_account': 'Delete Account',
      'faq_q1': 'How do I track a garbage truck?',
      'faq_a1': 'Navigate to the Track tab to see real-time locations and live route status.',
      'faq_q2': 'How is the ETA calculated?',
      'faq_a2': 'The ETA is based on the truck current GPS position and average speed.',
      'faq_q3': 'Why is the truck not visible?',
      'faq_a3': 'A truck may be finishing its route or experiencing signal loss.',
      'faq_q4': 'How do I file a complaint?',
      'faq_a4': 'Go to the Complaints tab and tap File a Complaint.',
      'support_desc': 'Reach out to us if you need help or have any inquiries.',
      'about_desc1': 'A comprehensive garbage truck tracking system designed for efficiency.',
      'about_desc2': 'Our mission is to provide real-time updates for a cleaner environment.',
      'edit_profile': 'Edit Profile',
      'contact_number': 'Contact Number',
    },
    'Filipino': {
      // Login & Common
      'login': 'Mag-login',
      'username': 'Username',
      'password': 'Password',
      'forgot_password': 'Nakalimutan ang Password?',
      'dont_have_account': "Wala pang account? ",
      'create_account': 'Gumawa ng Account',
      'verifying': 'Sinusuri...',
      'username_hint': 'Ilagay ang iyong napiling username',
      'password_hint': 'Ilagay ang iyong password',
      'brgy_title': 'Brgy. Balintawak, Lipa City',
      'app_name': 'Garbage Tracker',
      'terms': 'Kasunduan at Kondisyon',
      'privacy': 'Patakaran sa Privacy',
      'select_language': 'Pumili ng wika',
      'logout': 'Mag-logout',
      'cancel': 'Kanselahin',
      'save': 'I-save ang mga Pagbabago',
      'edit': 'I-edit',
      'close': 'Isara',
      'back': 'Bumalik',
      'next': 'Susunod',
      'success': 'Tagumpay',
      'error': 'Error',
      'all_rights_reserved': 'Lahat ng karapatan ay reserbado',

      // Legal Modals
      'terms_title': 'Kasunduan at Kondisyon',
      'privacy_title': 'Patakaran sa Privacy',
      'legal_accept': 'Tinatanggap Ko',
      'legal_decline': 'Tanggihan',

      // Registration
      'register': 'Magparehistro',
      'choose_role': 'Pumili ng Iyong Papel',
      'select_account_type': 'Pumili ng uri ng account para magpatuloy',
      'resident': 'Resident',
      'resident_sub': 'Subaybayan ang truck at maghain ng reklamo',
      'driver': 'Driver',
      'driver_sub': 'Pamahalaan ang ruta at koleksyon',
      'resident_reg': 'Rehistrasyon ng Resident',
      'driver_reg': 'Rehistrasyon ng Driver',
      'full_name': 'Buong Pangalan',
      'email': 'Email Address',
      'phone': 'Numero ng Telepono',
      'purok': 'Purok / Area',
      'address': 'Kumpletong Tirahan',
      'license': 'Numero ng Lisensya',
      'plate': 'Numero ng Plate',
      'preferred_truck': 'Gustong Truck',
      'register_btn': 'Gumawa ng Account',
      'already_have_account': 'May account na? ',

      // Forgot Password (3 Steps)
      'account_recovery': 'Pagbawi ng Account',
      'verification': 'Pagpapatunay',
      'enter_token': 'Ilagay ang Token',
      'step_1_title': 'I-reset ang Password',
      'step_2_title': 'I-verify ang Token',
      'step_3_title': 'Gumawa ng Bago',
      'step_1_of_3': 'Hakbang 1 ng 3: Patunayan ang iyong pagkakakilanlan',
      'step_2_of_3': 'Hakbang 2 ng 3: Ilagay ang 6-digit na code',
      'step_3_of_3': 'Hakbang 3 ng 3: I-secure ang iyong account',
      'send_verification': 'Ipadala ang Pagpapatunay',
      'verify_token_btn': 'I-verify ang Token',
      'reset_password_btn': 'I-reset ang Password',
      'confirm_password': 'Kumpirmahin ang Password',
      'otp_hint': '000000',
      'code_sent_to': 'Code na ipinadala sa:',

      // Dashboards (Resident)
      'home': 'Home',
      'track': 'Subaybayan',
      'complaints': 'Mga Reklamo',
      'settings': 'Mga Setting',
      'welcome_back': 'Maligayang Pagbabalik 👋',
      'active_trucks': 'Aktibong Truck',
      'estimated_time': 'Tinatayang Oras',
      'real_time_overview': 'Real-time na Pangkalahatang-ideya',
      'live_tracking': 'Live na Pagsubaybay',
      'full_map': 'Buong Mapa',
      'quick_actions': 'Mabilis na Aksyon',
      'track_trucks': 'Subaybayan ang Truck',
      'file_complaint': 'Maghain ng Reklamo',

      // Admin Panel
      'admin_panel': 'Admin Dashboard',
      'analytics': 'Analytics',
      'user_mgmt': 'Pamamahala ng User',
      'data_mgmt': 'Pamamahala ng Data',
      'system_logs': 'Mga Log ng System',
      'active_fleet': 'Aktibong Fleet',
      'coverage': 'Coverage',
      'routes_done': 'Tapos na Ruta',
      'issues': 'Mga Isyu',

      // Settings Specifics
      'profile_info': 'Impormasyon ng Profile',
      'notifications': 'Mga Abiso',
      'push_notifications': 'Push Notifications',
      'account_privacy': 'Account at Privacy',
      'change_password': 'Palitan ang Password',
      'help_support': 'Tulong at Suporta',
      'faqs': 'Mga FAQ',
      'contact_support': 'Makipag-ugnayan sa Suporta',
      'about': 'Tungkol Dito',
      'app_info': 'Impormasyon ng App',
      'language': 'Wika',
      'sign_out_q': 'Mag-logout?',
      'sign_out_confirm': 'Sigurado ka bang gusto mong tapusin ang iyong session?',

      // Registration Additional
      'purok_hint': 'Pumili ng iyong Purok',
      'address_hint': 'Ilagay ang iyong kumpletong tirahan',
      'email_hint': 'halimbawa@email.com',
      'phone_hint': '09XXXXXXXXX',
      'license_hint': 'Numero ng Driver License',
      'plate_hint': 'Numero ng Plate ng Truck',

      // 2FA Screen
      'two_step_verification': 'Two-Step na Pagpapatunay',
      'enter_6_digit': 'Ilagay ang 6-digit na code na ipinadala sa iyong email:',
      'verify_login': 'I-verify at Mag-login',
      'resend_code': 'Ipadala Muli ang Code',
      'back_to_login': 'Bumalik sa Login',
      'please_enter_otp': 'Mangyaring ilagay ang 6-digit na code',
      'otp_sent_success': 'Naipadala na ang bagong code!',
      'otp_verify_success': 'Matagumpay ang pagpapatunay!',

      // Driver Dashboard Details
      'vehicle_controls': 'Mga Kontrol ng Sasakyan',
      'start_trip': 'MAGSIMULA',
      'pause_trip': 'IPAHINGA',
      'full_truck': 'PUNO',
      'finish_trip': 'TAPOS',
      'collection_progress': 'Progreso ng Koleksyon',
      'manual_alert': 'Manu-manong Alerto',
      'simulation_mode': 'Simulation Mode',
      'real_gps': 'Tunay na GPS',
      'view_all_puroks': 'Tingnan Lahat ng Purok',
      'show_less': 'Ipakita ang Mas Kunti',
      'alert_history': 'Kasaysayan ng Alerto',
      'trip_finished_success': 'Matagumpay na natapos ang biyahe.',
      'finish_trip_q': 'Tapusin ang Biyahe?',
      'confirm_finish': 'Sigurado ka bang gusto mong tapusin ang biyahe?',

      // Resident Dashboard Details
      'no_notifications': 'Wala pang abiso.',
      'approaching': 'Papalapit na',
      'no_active_collection': 'Walang aktibong koleksyon',
      'real_time_locations': 'Real-time na lokasyon ng truck',
      'manage_preferences': 'Pamahalaan ang iyong mga kagustuhan',
      'receive_notifications': 'Makakuha ng mga update sa pagdating ng truck',
      'version': 'Bersyon',
      'last_updated': 'Huling Na-update',
      'data_management': 'Pamamahala ng Data',
      'view_my_data': 'Tingnan ang Aking Data',
      'clear_cache': 'I-clear ang Local Cache',
      'delete_account': 'I-delete ang Account',
      'faq_q1': 'Paano ko masusubaybayan ang truck ng basura?',
      'faq_a1': 'Pumunta sa tab na Subaybayan para makita ang real-time na lokasyon.',
      'faq_q2': 'Paano kinakalkula ang ETA?',
      'faq_a2': 'Ang ETA ay batay sa kasalukuyang posisyon ng GPS at bilis ng truck.',
      'faq_q3': 'Bakit hindi nakikita ang truck?',
      'faq_a3': 'Maaaring tinatapos ng truck ang ruta nito o nawawalan ng signal.',
      'faq_q4': 'Paano ako maghahain ng reklamo?',
      'faq_a4': 'Pumunta sa tab na Mga Reklamo at i-tap ang Maghain ng Reklamo.',
      'support_desc': 'Makipag-ugnayan sa amin kung kailangan mo ng tulong.',
      'about_desc1': 'Isang komprehensibong sistema ng pagsubaybay sa truck ng basura.',
      'about_desc2': 'Ang aming misyon ay magbigay ng mga update para sa mas malinis na kapaligiran.',
      'edit_profile': 'I-edit ang Profile',
      'contact_number': 'Numero ng Contact',
    },
    'Bisaya': {
      // Login & Common
      'login': 'Mag-login',
      'username': 'Username',
      'password': 'Password',
      'forgot_password': 'Nakalimot sa Password?',
      'dont_have_account': "Wala pa kay account? ",
      'create_account': 'Paghimo og Account',
      'verifying': 'Gisusi...',
      'username_hint': 'Ibutang ang imong gusto nga username',
      'password_hint': 'Ibutang ang imong password',
      'brgy_title': 'Brgy. Balintawak, Lipa City',
      'app_name': 'Garbage Tracker',
      'terms': 'Mga Termino ug Kondisyon',
      'privacy': 'Polisiya sa Pribasya',
      'select_language': 'Pilia ang imong pinulongan',
      'logout': 'Mag-logout',
      'cancel': 'Ikanselar',
      'save': 'I-save ang mga Kausaban',
      'edit': 'I-edit',
      'close': 'Isara',
      'back': 'Balik',
      'next': 'Sunod',
      'success': 'Kalamposan',
      'error': 'Error',
      'all_rights_reserved': 'Tanan nga katungod gigahin',

      // Legal Modals
      'terms_title': 'Mga Termino ug Kondisyon',
      'privacy_title': 'Polisiya sa Pribasya',
      'legal_accept': 'Dawaton Nako',
      'legal_decline': 'Balibad',

      // Registration
      'register': 'Magparehistro',
      'choose_role': 'Pilia ang Iyong Papel',
      'select_account_type': 'Pilia ang klase sa account para mopadayon',
      'resident': 'Resident',
      'resident_sub': 'Subaya ang truck ug pagsumite og reklamo',
      'driver': 'Driver',
      'driver_sub': 'Pagdumala sa ruta ug koleksyon',
      'resident_reg': 'Rehistrasyon sa Resident',
      'driver_reg': 'Rehistrasyon sa Driver',
      'full_name': 'Tibuok Pangalan',
      'email': 'Email Address',
      'phone': 'Numero sa Telepono',
      'purok': 'Purok / Area',
      'address': 'Tibuok Adres',
      'license': 'Numero sa Lisensya',
      'plate': 'Numero sa Plate',
      'preferred_truck': 'Gusto nga Truck',
      'register_btn': 'Paghimo og Account',
      'already_have_account': 'Naa nay account? ',
      'purok_hint': 'Pilia ang imong Purok',
      'address_hint': 'Ibutang ang imong tibuok adres',
      'email_hint': 'pananglitan@email.com',
      'phone_hint': '09XXXXXXXXX',
      'license_hint': 'Numero sa Driver License',
      'plate_hint': 'Numero sa Plate sa Truck',

      // Forgot Password (3 Steps)
      'account_recovery': 'Pagbawi sa Account',
      'verification': 'Pagmatuod',
      'enter_token': 'Ibutang ang Token',
      'step_1_title': 'I-reset ang Password',
      'step_2_title': 'I-verify ang Token',
      'step_3_title': 'Paghimo og Bag-o',
      'step_1_of_3': 'Lakang 1 sa 3: Pamatud-i ang imong pagkatawo',
      'step_2_of_3': 'Lakang 2 sa 3: Ibutang ang 6-digit nga code',
      'step_3_of_3': 'Lakang 3 sa 3: I-secure ang imong account',
      'send_verification': 'Ipadala ang Pagmatuod',
      'verify_token_btn': 'I-verify ang Token',
      'reset_password_btn': 'I-reset ang Password',
      'confirm_password': 'Kumpirmaha ang Password',
      'otp_hint': '000000',
      'code_sent_to': 'Code nga gipadala sa:',
      'verification_token': 'Token sa Pagmatuod',

      // 2FA Screen
      'two_step_verification': 'Two-Step nga Pagmatuod',
      'enter_6_digit': 'Ibutang ang 6-digit nga code nga gipadala sa imong email:',
      'verify_login': 'I-verify ug Mag-login',
      'resend_code': 'Ipadala Pag-usab ang Code',
      'back_to_login': 'Balik sa Login',
      'please_enter_otp': 'Palihog ibutang ang 6-digit nga code',
      'otp_sent_success': 'Napada na ang bag-ong code!',
      'otp_verify_success': 'Malamposon ang pagmatuod!',

      // Dashboards (Resident)
      'home': 'Home',
      'track': 'Pagsubaybay',
      'complaints': 'Mga Reklamo',
      'settings': 'Mga Setting',
      'welcome_back': 'Maayong Pagbalik 👋',
      'active_trucks': 'Aktibong mga Truck',
      'estimated_time': 'Gibanabana nga Oras',
      'real_time_overview': 'Real-time nga Kinatibuk-an',
      'live_tracking': 'Live nga Pagsubaybay',
      'full_map': 'Tibuok Mapa',
      'quick_actions': 'Dali nga mga Aksyon',
      'track_trucks': 'Pagsubaybay sa Truck',
      'file_complaint': 'Pagsumite og Reklamo',
      'no_notifications': 'Wala pa kay notipikasyon.',
      'approaching': 'Paduol na',
      'no_active_collection': 'Walay aktibong koleksyon',
      'real_time_locations': 'Real-time nga lokasyon sa trak',

      // Driver Dashboard Specifics
      'vehicle_controls': 'Mga Kontrol sa Sakyanan',
      'start_trip': 'MAGSUGOD',
      'pause_trip': 'IPAHULAY',
      'full_truck': 'PUNO',
      'finish_trip': 'HUMAN',
      'collection_progress': 'Progreso sa Koleksyon',
      'manual_alert': 'Manwal nga Alerto',
      'simulation_mode': 'Simulation Mode',
      'real_gps': 'Tinuod nga GPS',
      'view_all_puroks': 'Tan-awa Tanan Purok',
      'show_less': 'Ipakita ang Gamay',
      'alert_history': 'Kasaysayan sa Alerto',
      'trip_finished_success': 'Malamposon nga nahuman ang biyahe.',
      'finish_trip_q': 'Humanon ang Biyahe?',
      'confirm_finish': 'Sigurado ka ba nga gusto nimong humanon ang biyahe?',

      // Admin Panel
      'admin_panel': 'Admin Dashboard',
      'analytics': 'Analytics',
      'user_mgmt': 'Pagdumala sa User',
      'data_mgmt': 'Pagdumala sa Data',
      'system_logs': 'Mga Log sa System',
      'active_fleet': 'Aktibong Fleet',
      'coverage': 'Coverage',
      'routes_done': 'Human na Ruta',
      'issues': 'Mga Isyu',

      // Settings Specifics
      'profile_info': 'Impormasyon sa Profile',
      'notifications': 'Mga Notipikasyon',
      'push_notifications': 'Push Notifications',
      'account_privacy': 'Account ug Pribasya',
      'change_password': 'Usba ang Password',
      'help_support': 'Tabang ug Suporta',
      'faqs': 'Mga FAQ',
      'contact_support': 'Kontaka ang Suporta',
      'about': 'Mahitungod',
      'app_info': 'Impormasyon sa App',
      'language': 'Pinulongan',
      'sign_out_q': 'Mag-logout?',
      'sign_out_confirm': 'Sigurado ka ba nga gusto nimong tapuson ang imong session?',
    },
  };

  final List<String> languages = ['English', 'Filipino', 'Bisaya'];

  Future<void> init() async {
    final prefs = await SharedPreferences.getInstance();
    _currentLanguage = prefs.getString('selected_language') ?? 'English';
    if (_currentLanguage == 'English (UK)') _currentLanguage = 'English';
    notifyListeners();
  }

  Future<void> setLanguage(String language) async {
    if (!languages.contains(language)) return;
    _currentLanguage = language;
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString('selected_language', language);
    notifyListeners();
  }

  String translate(String key) {
    return _translations[_currentLanguage]?[key] ?? _translations['English']![key] ?? key;
  }
}
